# Generated by Django 5.2.13 on 2026-04-12 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('primary_descriptor', models.CharField(blank=True, max_length=100)),
                ('secondary_descriptor', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('supc', models.CharField(blank=True, db_index=True, max_length=20)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.product')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'description')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_description', models.CharField(blank=True, max_length=500)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('case_size', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.product')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['vendor', 'invoice_date'], name='myapp_invoi_vendor__9cd17a_idx'), models.Index(fields=['product', 'invoice_date'], name='myapp_invoi_product_3f4e97_idx')],
            },
        ),
    ]
