# Generated by Django 5.2.13 on 2026-04-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='match_confidence',
            field=models.CharField(blank=True, choices=[('code', 'SUPC Code Match'), ('exact', 'Exact Description Match'), ('vendor_exact', 'Vendor-Scoped Exact'), ('vendor_fuzzy', 'Vendor-Scoped Fuzzy'), ('global_exact', 'Global Exact'), ('global_fuzzy', 'Global Fuzzy'), ('stripped-fuzzy', 'Stripped Prefix Fuzzy'), ('unmatched', 'Unmatched')], max_length=20),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='price_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
