# Generated by Django 5.2.13 on 2026-04-17 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_invoicelineitem_match_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('headcount', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Census',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('yield_servings', models.IntegerField(default=40)),
                ('source_doc', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_raw', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='myapp.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='PrepTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('assignee', models.CharField(blank=True, choices=[('sean', 'Sean'), ('albert', 'Albert')], max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_tasks', to='myapp.recipe')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='myapp_prept_date_00864b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_slot', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('late', 'Late Plate')], max_length=20)),
                ('dish_freetext', models.CharField(blank=True, max_length=200)),
                ('assignee', models.CharField(blank=True, choices=[('sean', 'Sean'), ('albert', 'Albert')], max_length=20)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.recipe')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='myapp_menu_date_870199_idx')],
                'unique_together': {('date', 'meal_slot')},
            },
        ),
    ]
