# Generated by Django 5.2.13 on 2026-04-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_census_recipe_recipeingredient_preptask_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal_slot',
            field=models.CharField(choices=[('cold_breakfast', 'Cold Breakfast'), ('hot_breakfast', 'Hot Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20),
        ),
    ]
