# Generated by Django 5.2.13 on 2026-04-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_menu_meal_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ingredients_raw',
            field=models.TextField(blank=True),
        ),
    ]
