# Generated by Django 5.2.13 on 2026-04-17 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_menu_ingredients_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, help_text='If set, this ingredient is another recipe (composed meal component).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in', to='myapp.recipe'),
        ),
    ]
