# Generated by Django 5.2.13 on 2026-04-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_recipeingredient_sub_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='additional_recipes',
            field=models.ManyToManyField(blank=True, related_name='menus_as_side', to='myapp.recipe'),
        ),
    ]
