# Generated by Django 5.2.13 on 2026-04-18 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_menu_additional_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuFreetextComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('position', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freetext_components', to='myapp.menu')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
