# Generated by Django 5.2.13 on 2026-04-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_menufreetextcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='fat_health',
            field=models.CharField(blank=True, choices=[('F', 'Fatty'), ('H', 'Healthy')], help_text="Sean's (F)=Fatty / (H)=Healthy oscillation tag.", max_length=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='popularity',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Popularity among residents (from Menu Guide highlight color).', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.CharField(blank=True, choices=[('beef', 'Beef'), ('chicken', 'Chicken'), ('pork', 'Pork'), ('turkey', 'Turkey'), ('seafood', 'Seafood'), ('veg', 'Vegetarian'), ('eggs', 'Eggs / Breakfast'), ('other', 'Other')], help_text='Primary protein; used for menu arrangement rules.', max_length=20),
        ),
    ]
