# Generated by Django 5.2.13 on 2026-04-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_recipe_fat_health_recipe_popularity_recipe_protein'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSkipNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_raw', models.CharField(max_length=200, unique=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
