# Generated by Django 5.2.13 on 2026-04-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_ingredientskipnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='yield_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Edible yield % from Book of Yields / USDA (e.g., 81 for peeled carrots). Null = no adjustment. Used to scale AP order quantity.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Edible-portion quantity the recipe calls for.', max_digits=8, null=True),
        ),
    ]
