# Generated by Django 5.2.13 on 2026-04-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_recipeingredient_yield_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='yield_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Edible yield % — only used if yield_ref is not set. E.g., 81 for peeled carrots. Null = no adjustment.', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='YieldReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=200)),
                ('prep_state', models.CharField(blank=True, help_text="e.g., 'peeled', 'grated', 'sliced about 1/4 in.'", max_length=200)),
                ('section', models.CharField(choices=[('herbs_spices', 'Dry Herbs and Spices'), ('fresh_herbs', 'Fresh Herbs'), ('vegetables', 'Vegetables'), ('fruit', 'Fruit'), ('canned', 'Canned Foods'), ('dry_legumes', 'Dry Legumes'), ('grains', 'Rice/Grains/Cereals'), ('pasta', 'Pasta'), ('nuts_seeds', 'Nuts and Seeds'), ('flour', 'Flour/Meal/Bran/Crumbs'), ('sweeteners', 'Sweeteners'), ('baking', 'Special Baking Items'), ('fats_oils', 'Fats and Oils'), ('condiments', 'Condiments'), ('liquids', 'Liquids'), ('dairy', 'Dairy Products'), ('beverages', 'Coffee/Tea/Cocoa'), ('meats', 'Meats'), ('seafood', 'Seafood'), ('poultry', 'Poultry')], db_index=True, max_length=30)),
                ('yield_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ap_unit', models.CharField(blank=True, help_text="As-purchased unit, e.g. 'pound', 'bunch'.", max_length=40)),
                ('ap_weight_oz', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('trimmed_unit', models.CharField(blank=True, max_length=40)),
                ('trimmed_weight_oz', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('trimmed_count', models.IntegerField(blank=True, null=True)),
                ('measures_per_ap', models.DecimalField(blank=True, decimal_places=3, help_text='e.g., cups per AP unit', max_digits=8, null=True)),
                ('ounce_weight_per_cup', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('extras', models.JSONField(blank=True, help_text='Section-specific fields (cooked yield, raw→cooked ratios, etc.)', null=True)),
                ('source', models.CharField(default='Book of Yields 8e', max_length=50)),
                ('source_ref', models.CharField(blank=True, help_text="e.g., 'p.50'", max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yield_refs', to='myapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='yield_ref',
            field=models.ForeignKey(blank=True, help_text='If set, effective yield comes from this reference entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_ingredients', to='myapp.yieldreference'),
        ),
        migrations.AddIndex(
            model_name='yieldreference',
            index=models.Index(fields=['section', 'ingredient'], name='myapp_yield_section_cbaeb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='yieldreference',
            unique_together={('ingredient', 'prep_state', 'section')},
        ),
    ]
