# Generated by Django 5.2.13 on 2026-04-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_recipeingredient_yield_pct_yieldreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPortionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('soup_salad_bread', 'Soup, Salad, Bread'), ('beef_entrees', 'Beef Entrees'), ('chicken_entrees', 'Chicken Entrees'), ('seafood_entrees', 'Seafood Entrees'), ('pork_entrees', 'Pork Entrees'), ('veal', 'Veal'), ('pasta_entree', 'Pasta Entree'), ('potatoes', 'Potatoes'), ('desserts', 'Desserts'), ('beverages', 'Beverages'), ('breakfast_items', 'Breakfast Items'), ('lunch_items', 'Lunch Items'), ('hors_doeuvre', "Hors d'Oeuvre")], max_length=32)),
                ('average_measure', models.CharField(blank=True, max_length=40)),
                ('low_range', models.CharField(blank=True, max_length=40)),
                ('high_range', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(default='Book of Yields 8e Ch 15', max_length=60)),
                ('source_ref', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['category', 'menu_item'],
                'indexes': [models.Index(fields=['category', 'menu_item'], name='myapp_stand_categor_5727e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'menu_item'), name='uniq_portion_by_category_item')],
            },
        ),
    ]
