# Generated by Django 5.2.13 on 2026-04-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_match_confidence_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='conflicts',
            field=models.JSONField(blank=True, default=list, help_text='Dietary conflicts this recipe CONTAINS (Big 15 vocab). Used for client-dietary-safety matching.'),
        ),
    ]
