# Generated by Django 5.2.13 on 2026-04-20 00:19

import django.db.models.deletion
from django.db import migrations, models


def backfill_level_from_source_doc(apps, schema_editor):
    """Infer Recipe.level from the source_doc folder path.

    - Prep Components/ or Baking/ subparts → 'recipe' (default)
    - Composed Meals/ → 'composed_dish'
    - Has any RecipeIngredient.sub_recipe set → 'composed_dish'
    - Everything else → 'recipe' (conservative)

    Sean can re-level via admin. The matcher (link_menus_to_recipes) will
    benefit immediately from composed_dish flagging Taco Lasagna, etc."""
    Recipe = apps.get_model('myapp', 'Recipe')
    for r in Recipe.objects.all():
        src = (r.source_doc or '').replace('\\', '/').lower()
        has_sub = r.ingredients.filter(sub_recipe__isnull=False).exists()
        if has_sub or 'composed meals/' in src:
            r.level = 'composed_dish'
        else:
            r.level = 'recipe'
        r.save(update_fields=['level'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_recipe_conflicts'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Only one version per lineage is current. Menu links prefer current.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='level',
            field=models.CharField(choices=[('recipe', 'Recipe (ingredients only)'), ('composed_dish', 'Composed Dish (recipes + ingredients)'), ('meal', 'Meal (plate-level menu entry)')], default='recipe', help_text='recipe = ingredients only; composed_dish = has sub_recipes; meal = plate-level menu entry.', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='parent_recipe',
            field=models.ForeignKey(blank=True, help_text='If this is V2+, points to the prior version (V1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='myapp.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='version_number',
            field=models.IntegerField(default=1, help_text='1 for trunk, 2+ for later versions of the same lineage.'),
        ),
        migrations.RunPython(backfill_level_from_source_doc, reverse_noop),
    ]
