# Generated by Django 5.2.13 on 2026-04-20 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_recipe_authoring_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepped_qty', models.DecimalField(blank=True, decimal_places=3, help_text="Amount prepped for service, in the dish's native unit.", max_digits=8, null=True)),
                ('post_service_leftover_qty', models.DecimalField(blank=True, decimal_places=3, help_text='Amount leftover after service; goes to client fridge.', max_digits=8, null=True)),
                ('discarded_qty', models.DecimalField(blank=True, decimal_places=3, help_text='Amount discarded at shelf-life end. Usually 0.', max_digits=8, null=True)),
                ('discarded_at', models.DateTimeField(blank=True, help_text='When disposal happened (typically day 5 of leftover shelf life).', null=True)),
                ('unit', models.CharField(blank=True, help_text='Per-dish convention: pans, portions, lbs, etc.', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='myapp.menu')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['menu'], name='myapp_meals_menu_id_0eafd3_idx'), models.Index(fields=['discarded_at'], name='myapp_meals_discard_412ea4_idx')],
            },
        ),
    ]
