# Generated by Django 5.2.13 on 2026-04-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_mealservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='learned_consumption_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Rolling avg total_consumption_rate from last ~10 services. Null when fewer than 3 samples (fall back to 0.80 baseline).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='learned_sample_count',
            field=models.IntegerField(default=0, help_text='Number of MealService samples backing learned_consumption_rate.'),
        ),
    ]
