# Generated by Django 5.2.13 on 2026-04-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_recipe_learned_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='extended_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Line total (qty × unit_price) as printed on the invoice. For Sysco, typically equals unit_price. For Farm Art and other per-unit priced vendors, this captures the qty multiplier.', max_digits=10, null=True),
        ),
    ]
