# Generated by Django 5.2.13 on 2026-04-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_invoicelineitem_extended_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='valid_slots',
            field=models.JSONField(blank=True, default=list, help_text='Menu slots where this recipe belongs (cold_breakfast/hot_breakfast/lunch/dinner). Empty = appears in any slot.'),
        ),
    ]
