# Generated by Django 5.2.13 on 2026-04-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_recipe_valid_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='section_hint',
            field=models.CharField(blank=True, db_index=True, help_text="Section header from the invoice (e.g. 'DAIRY', 'CHEMICAL & JANITORIAL'). Used to categorize unknown-code rows where the OCR dropped the description column.", max_length=60),
        ),
    ]
