# Generated by Django 5.2.13 on 2026-04-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_invoicelineitem_section_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_case_size',
            field=models.CharField(blank=True, help_text="Canonical pack size for this product (e.g. '4/1GAL'). Fallback when an InvoiceLineItem has no case_size from its raw description. Inferred from mode of historical invoices by `infer_product_default_case_sizes`.", max_length=30),
        ),
    ]
