# Generated by Django 5.2.13 on 2026-04-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_more_piece_weight_yields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='price_per_pound',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Per-pound price computed directly by the parser. Populated for Sysco catch-weight (MEATS/POULTRY/SEAFOOD) and all Exceptional Foods rows where the vendor bills per-lb. Null elsewhere (Farm Art, PBM, Delaware Linen, Colonial). Consumers should prefer this field over reverse-engineering $/lb from unit_price + case_size.', max_digits=10, null=True),
        ),
    ]
