# Generated by Django 5.2.13 on 2026-04-26 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_invoicelineitem_match_confidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMappingProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_description', models.CharField(max_length=500)),
                ('score', models.IntegerField(blank=True, help_text='Fuzzy score 0-100 from the source scorer.', null=True)),
                ('confidence_tier', models.CharField(blank=True, help_text='vendor_fuzzy / fuzzy / stripped_fuzzy / etc.', max_length=30)),
                ('source', models.CharField(choices=[('mapper_quarantine', 'Mapper Quarantine (fuzzy held at write)'), ('discover_unmapped', 'Discover Unmapped Scan')], default='mapper_quarantine', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_proposals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('suggested_product', models.ForeignKey(blank=True, help_text="The mapper's best guess. Null when the human is inventing a new canonical.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_proposals', to='myapp.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_proposals', to='myapp.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='myapp_produ_status_16eb78_idx')],
                'unique_together': {('vendor', 'raw_description')},
            },
        ),
    ]
