# Generated by Django 5.2.13 on 2026-04-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_productmappingproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='match_confidence',
            field=models.CharField(blank=True, choices=[('code', 'SUPC Code Match'), ('exact', 'Exact Description Match'), ('vendor_exact', 'Vendor-Scoped Exact'), ('vendor_fuzzy', 'Vendor-Scoped Fuzzy'), ('fuzzy', 'Fuzzy Match'), ('stripped_fuzzy', 'Stripped Prefix Fuzzy'), ('subset_match', 'Subset Match (canonical tokens ⊆ raw)'), ('keyword_batch', 'Keyword Batch (Human)'), ('manual_review', 'Manual Review (Human)'), ('non_product', 'Non-Product (surcharge/fee/credit)'), ('unmatched', 'Unmatched'), ('unmatched_drift', 'Unmatched (Sheet/DB Drift)')], max_length=20),
        ),
    ]
