# Generated by Django 5.2.13 on 2026-04-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_invoicelineitem_match_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmappingproposal',
            name='final_canonical_text',
            field=models.CharField(blank=True, help_text='Canonical name the reviewer actually saved (may differ from suggested).', max_length=200),
        ),
        migrations.AddField(
            model_name='productmappingproposal',
            name='suggested_canonical_text',
            field=models.CharField(blank=True, help_text='Auto-derived canonical name suggestion shown in the create form.', max_length=200),
        ),
    ]
