# Generated by Django 5.2.13 on 2026-05-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_invoicelineitem_match_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prep_state',
            field=models.CharField(blank=True, help_text='Per-category form descriptor. Cheese: Whole/Shredded/Sliced/Loaf/Balls/Wedge/Crumbled. Captures price-differential between bought-prepped and prepped-in-house forms. Will phase out as in-house prep replaces purchased pre-prep.', max_length=30),
        ),
    ]
