# Generated by Django 5.2.13 on 2026-05-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_smallwares_convention_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='case_pack_count',
            field=models.IntegerField(blank=True, help_text="Units per case (e.g. 60 patties/case for Burgers 60/5.3OZ). First half of vendor's pack-size column. NULL when not applicable (catch-weight rows, single-unit bulk, etc.).", null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='case_pack_unit_size',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Size of each unit (e.g. 5.3 oz for 60/5.3OZ Burgers). Decimal-tolerant (parser caps at 48 missed 5.3oz patties; case_size_decoder handles up to 2000+ with decimals).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='case_pack_unit_uom',
            field=models.CharField(blank=True, help_text='Unit-of-size for each pack member: OZ / LB / CT / PT / DZ / GAL.', max_length=10),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='case_total_weight_lb',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total case weight in lb — derived canonical for $/lb math. = case_pack_count × case_pack_unit_size (with unit conversion). Replaces the parse-string-and-pray flow in synergy_sync.calc_price_per_lb.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='count_per_lb_high',
            field=models.IntegerField(blank=True, help_text="High end of per-lb count grade (e.g. 14 for bacon '10/14'). Recipe cost = ($/lb / avg(low,high)) × strips_called_for.", null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='count_per_lb_low',
            field=models.IntegerField(blank=True, help_text="Low end of per-lb count grade (e.g. 10 for bacon '10/14'). Used by recipe cost calc for per-piece pricing. Extracted from raw_description by per-vendor parsers.", null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='purchase_uom',
            field=models.CharField(blank=True, help_text="Vendor's U/M column verbatim. EACH / CASE / LB / DZ / etc. Free varchar — controlled vocabulary will emerge from audit after backfill. Distinguishes per-piece vs per-case pricing for Farm Art (Celery 3 stalks @ $2.60/EACH = $7.72 vs $7.72/case).", max_length=10),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Quantity ordered/shipped from the invoice line. Exceptional catch-weight = actual shipped lbs (e.g. 8.56). Farm Art / PBM / Delaware = qty in vendor's U/M (often 1.0 CASE). Sysco = always 1 (one case per line). NULL when parser couldn't extract.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_class',
            field=models.CharField(blank=True, choices=[('', '— unset —'), ('weighed', 'Weighed (proteins, cheese — $/lb pricing, scale required)'), ('counted_with_weight', 'Counted-with-weight (uniform packs — count blocks/tubs/bottles)'), ('counted_with_volume', 'Counted-with-volume (gallons/quarts/pints — count containers)')], help_text="Inventory class — drives sheet F+G column logic + recipe cost dispatch. Weighed: F=total lb, G='#'. Counted-with-weight: F=count, G='1# Print' / '5# Tub' / etc. Counted-with-volume: F=count, G='Gal' / 'Qt' / 'Pt'. Future: type-check fuzzy mapper (reject yogurt→shrimp class mismatch).", max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_unit_descriptor',
            field=models.CharField(blank=True, help_text="Human-readable unit descriptor that lands in sheet col G. Examples: '1# Print' / '5# Tub' / '5.3 oz Patty' / 'Half-pint Clamshell' / 'Gal' / 'Btl' / 'Ea'. Replaces sheet col G's ad-hoc strings with controlled values.", max_length=60),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='case_size',
            field=models.CharField(blank=True, help_text='LEGACY string field — preserved for backward compat + audit. Holds 6+ semantic shapes (vendor weight, pack format, merged count×size, volume container count, catch-weight, U/M token, range). Consumers should prefer the structured fields below (quantity, purchase_uom, case_pack_*) when populated. Deprecation target: post-Phase-3 of structured schema migration.', max_length=100),
        ),
    ]
