# Generated by Django 5.2.13 on 2026-05-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_structured_invoice_line_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalDriftRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_canonical', models.CharField(help_text='canonical_name string of the rejected proposal target.', max_length=200)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Optional reason for the rejection.')),
                ('product_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_rejections', to='myapp.productmapping')),
            ],
            options={
                'ordering': ['-rejected_at'],
                'constraints': [models.UniqueConstraint(fields=('product_mapping', 'rejected_canonical'), name='uniq_drift_rejection_per_pair')],
            },
        ),
    ]
