# Generated by Django 5.2.13 on 2026-05-02 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_canonicaldriftrejection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmappingproposal',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productmappingproposal',
            name='source',
            field=models.CharField(choices=[('mapper_quarantine', 'Mapper Quarantine (fuzzy held at write)'), ('discover_unmapped', 'Discover Unmapped Scan'), ('drift_audit', 'Canonical Drift Audit (PM re-evaluation)')], default='mapper_quarantine', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='productmappingproposal',
            unique_together={('vendor', 'raw_description', 'source', 'suggested_product')},
        ),
        migrations.AddIndex(
            model_name='productmappingproposal',
            index=models.Index(fields=['vendor', 'raw_description'], name='myapp_produ_vendor__9439ea_idx'),
        ),
    ]
