# Generated by Django 5.2.13 on 2026-05-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_alter_productmappingproposal_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanonicalDriftRejection',
        ),
    ]
