# Generated by Django 5.2.13 on 2026-05-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_delete_canonicaldriftrejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmappingproposal',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('', '— none —'), ('wrong_canonical', 'Wrong canonical (suggestion is the wrong product)'), ('not_a_product', 'Not a product (boilerplate / fee / line noise)'), ('typo_or_garble', 'Typo or OCR garble in raw description'), ('different_class', 'Different inventory class (weighed vs counted)'), ('belongs_elsewhere', 'Belongs in a different canonical that exists'), ('needs_new_canonical', 'Needs a new canonical (none exists yet)'), ('other', 'Other (see notes)')], db_index=True, help_text='Categorical reason for the rejection — drives audit filtering + future quality metrics.', max_length=30),
        ),
    ]
