# Generated by Django 5.2.13 on 2026-05-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_alter_invoicelineitem_match_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmappingproposal',
            name='source',
            field=models.CharField(choices=[('mapper_quarantine', 'Mapper Quarantine (fuzzy held at write)'), ('discover_unmapped', 'Discover Unmapped Scan'), ('drift_audit', 'Canonical Drift Audit (PM re-evaluation)'), ('suspect_audit', 'Suspect-Mappings Audit (zero token overlap)'), ('supc_recovery', 'Sysco SUPC Cross-Cache Recovery')], default='mapper_quarantine', max_length=30),
        ),
    ]
