# Generated by Django 5.2.13 on 2026-05-05 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_add_observed_confidence_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text="Vendor's SKU code (e.g. 'EGS', 'ID12')", max_length=40)),
                ('raw_description', models.CharField(help_text="Vendor's display name; matches ProductMapping.description on invoices", max_length=500)),
                ('unit', models.CharField(help_text='Order unit: CASE / HALF_CASE / EACH / LB / BAG / BOX / FLAT / BUSHEL / KILOGRAM / GALLON / CLAMSHELL_BOX / UNIT / etc. Vendor-specific vocabulary.', max_length=30)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ach_discount_pct', models.DecimalField(decimal_places=4, default=0, help_text='Decimal e.g. 0.01 = 1% ACH discount.', max_digits=5)),
                ('captured_at', models.DateField(help_text='Date the source order guide was captured.')),
                ('source_file', models.CharField(blank=True, max_length=200)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_entries', to='myapp.vendor')),
            ],
            options={
                'ordering': ['vendor', 'sku', 'unit'],
                'indexes': [models.Index(fields=['vendor', 'sku'], name='myapp_vendo_vendor__f97064_idx')],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'sku', 'unit'), name='uniq_vendor_sku_unit')],
            },
        ),
    ]
