# Generated by Django 5.2.13 on 2026-05-06 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_vendorpricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='canonical_vendor_pricelist',
            field=models.ForeignKey(blank=True, help_text='Canonical vendor SKU this line item represents. Identity pointer; does NOT replace historical price fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_invoice_lines', to='myapp.vendorpricelist'),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['canonical_vendor_pricelist', 'invoice_date'], name='myapp_invoi_canonic_fbccbd_idx'),
        ),
    ]
