# Generated by Django 5.2.13 on 2026-05-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_canonical_vpl_fk_on_ili'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceValidationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=20)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('items_count', models.IntegerField(default=0)),
                ('items_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, help_text='Printed INVOICE TOTAL extracted from the invoice.', max_digits=10, null=True)),
                ('invoice_gap', models.DecimalField(blank=True, decimal_places=2, help_text='items_sum − invoice_total. Negative = items missing.', max_digits=10, null=True)),
                ('invoice_gap_pct', models.DecimalField(blank=True, decimal_places=2, help_text='abs(invoice_gap) / invoice_total × 100.', max_digits=6, null=True)),
                ('sections_total', models.IntegerField(default=0, help_text='Number of distinct sections detected.')),
                ('sections_reconciled', models.IntegerField(default=0, help_text='Sections where parser_sum matches printed GROUP TOTAL within $0.50.')),
                ('sections_with_gap', models.IntegerField(default=0, help_text='Sections with diff > $0.50.')),
                ('section_reconciliation', models.JSONField(blank=True, default=list, help_text='List of {section, parser_sum, printed_total, diff_abs, diff_pct, item_count}.')),
                ('cache_hashes', models.JSONField(blank=True, default=list, help_text='OCR cache file SHA256 hashes that fed this validation.')),
                ('status', models.CharField(choices=[('pass', 'PASS — all sections + invoice_total reconcile within tolerance'), ('review', 'REVIEW — section-level diffs exceed tolerance'), ('fail', 'FAIL — items_sum vs invoice_total >10% off'), ('partial', 'PARTIAL — invoice_total or section data missing')], db_index=True, default='partial', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('last_validated', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vendor')),
            ],
            options={
                'ordering': ['-invoice_date', 'vendor', 'invoice_number'],
                'indexes': [models.Index(fields=['status', '-last_validated'], name='myapp_invoi_status_d727a4_idx'), models.Index(fields=['vendor', '-invoice_date'], name='myapp_invoi_vendor__bbf055_idx')],
                'unique_together': {('vendor', 'invoice_number')},
            },
        ),
    ]
