# Generated by Django 5.2.13 on 2026-05-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_invoicevalidationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='math_flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='match_confidence',
            field=models.CharField(blank=True, choices=[('code', 'SUPC Code Match'), ('exact', 'Exact Description Match'), ('vendor_exact', 'Vendor-Scoped Exact'), ('vendor_fuzzy', 'Vendor-Scoped Fuzzy'), ('fuzzy', 'Fuzzy Match'), ('stripped_fuzzy', 'Stripped Prefix Fuzzy'), ('subset_match', 'Subset Match (canonical tokens ⊆ raw)'), ('keyword_batch', 'Keyword Batch (Human)'), ('manual_review', 'Manual Review (Human)'), ('auto_repoint', 'Auto-Repointed (live mapper produced different canonical)'), ('non_product', 'Non-Product (surcharge/fee/credit)'), ('unmatched', 'Unmatched'), ('unmatched_drift', 'Unmatched (Sheet/DB Drift)'), ('unmatched_garbled', 'Unmatched (Parser Garble)'), ('unmatched_class_mismatch', 'Unmatched (Class Mismatch Guard)'), ('unmatched_repointed', 'Unmatched (Repointed by Cleanup)'), ('vendor_fuzzy_pending', 'Vendor Fuzzy (Quarantined, Pending Review)'), ('subset_match_pending', 'Subset Match (Quarantined, Pending Review)'), ('stripped_fuzzy_pending', 'Stripped Fuzzy (Quarantined, Pending Review)')], max_length=30),
        ),
    ]
