# Generated by Django 5.2.13 on 2026-05-09 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_math_flagged_on_ili'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='user_edited',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoicevalidationstatus',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicevalidationstatus',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who explicitly verified this invoice. NULL means auto-validation only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvoiceLineEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('before', models.JSONField(default=dict, help_text='Snapshot of editable ILI fields BEFORE this edit. Keys: quantity, unit_price, extended_amount, case_size, raw_description.')),
                ('after', models.JSONField(default=dict, help_text='Snapshot of editable ILI fields AFTER this edit.')),
                ('reason', models.CharField(blank=True, choices=[('', '— none —'), ('manual_correction', 'Manual correction (parser error / OCR garble)'), ('damaged_transit', 'Damaged in transit (driver credit on paper)'), ('short_ship', 'Short ship (delivered less than billed)'), ('quality_issue', 'Quality issue / return'), ('pricing_correction', 'Pricing correction'), ('handwritten_addition', 'Hand-written invoice / line addition'), ('handwritten_credit', 'Hand-written credit (driver wrote on paper)'), ('portal_credit_match', 'Reconciled to vendor portal credit'), ('other', 'Other (see note)')], help_text='Categorical reason. Drives downstream filtering (e.g. credits feed L2 InvoiceCredit reconciliation).', max_length=30)),
                ('note', models.TextField(blank=True, help_text='Free-text context for the edit. Why, what was on paper vs what parser captured, etc.')),
                ('cleared_math_flag', models.BooleanField(default=False, help_text='True if this edit caused math_flagged to flip from True → False (math now reconciles).')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='myapp.invoicelineitem')),
            ],
            options={
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['ili', '-edited_at'], name='myapp_invoi_ili_id_b1d430_idx')],
            },
        ),
    ]
