# Generated by Django 5.2.13 on 2026-05-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_p12_edit_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, help_text="Vendor-extracted invoice number (e.g. Sysco '775687424', Farm Art '1654186'). Stable across re-photo/reprocess cycles. Phase 4c (Sean 2026-05-10): primary dedup key, replacing source_file-based dedup. Empty when extraction unreliable (Colonial; some PBM/Delaware) — falls back to legacy keys.", max_length=20),
        ),
    ]
