# Generated by Django 5.2.13 on 2026-05-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_invoicelineitem_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='vendor_item_code',
            field=models.CharField(blank=True, db_index=True, help_text="Vendor's catalog code for this line item (Sysco SUPC, Farm Art item code, etc.). Stable across parser versions; preferred dedup key over raw_description.", max_length=32),
        ),
    ]
