# Generated by Django 5.2.13 on 2026-05-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_invoicelineitem_vendor_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicevalidationstatus',
            name='credits_pending',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='$ of audit edits with credit-pending reason (damaged_transit/short_ship/quality_issue/handwritten_credit). Expected credit-memo amount from vendor.', max_digits=10, null=True),
        ),
    ]
