# Generated by Django 5.2.13 on 2026-05-28 17:44

from django.db import migrations, models


def _null_existing_created_at(apps, schema_editor):
    """Existing menus predate instrumentation — NULL their created_at so the
    Flow metric counts only cells authored AFTER this migration. auto_now_add
    backfills existing rows with now(); we don't want that for the leading
    indicator (it would make every historical cell look 'authored this cycle').
    .update() bypasses auto_now_add, so it sets NULL directly."""
    Menu = apps.get_model('myapp', 'Menu')
    Menu.objects.update(created_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0074_invoicevalidationstatus_credits_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Authoring timestamp — drives the recipe-coverage Flow metric (% of newly-authored cells that got a recipe at authoring). NULL on rows that predate instrumentation (2026-05-28).', null=True),
        ),
        migrations.RunPython(_null_existing_created_at, migrations.RunPython.noop),
    ]
