# Generated by Django 5.2.13 on 2026-06-08 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_menu_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('qb_class', models.CharField(blank=True, help_text='QuickBooks Class name/code this account maps to (1:1).', max_length=40)),
                ('is_default', models.BooleanField(default=False, help_text='Account untagged invoices fall to (Food/Kitchen). Exactly one.')),
                ('is_food_budget', models.BooleanField(default=False, help_text='Included in food-budget / COGS aggregations. Account-aware consumers filter on this; account-blind (price/mapping) ignore it.')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Department/cost-center this line is attributed to. NULL = Food/Kitchen default. Drives budget/COGS filtering only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='myapp.account'),
        ),
    ]
