# Generated by Django 5.2.13 on 2026-06-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_seed_accounts_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carb_g_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_g_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fdc_id',
            field=models.CharField(blank=True, db_index=True, help_text='USDA FoodData Central ID this product is matched to — source of the per-100g macros below.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber_g_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kcal_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_confidence',
            field=models.CharField(blank=True, choices=[('', '— unmatched —'), ('auto', 'Auto-matched (high-confidence fuzzy → FDC)'), ('reviewed', 'Human-reviewed / confirmed'), ('estimated', 'Estimated (category proxy, no direct FDC match)')], help_text='Provenance of the macro profile — mirrors match_confidence. Drives the coverage % in the provided-nutrition rollup so the number never overstates its own accuracy.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='protein_g_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
