# Generated by Django 5.2.13 on 2026-06-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0078_product_carb_g_per_100g_product_fat_g_per_100g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutrition_confidence',
            field=models.CharField(blank=True, choices=[('', '— unmatched —'), ('auto', 'Auto-matched (high-confidence fuzzy → FDC)'), ('ai_reviewed', 'AI-reviewed (Claude-curated; spot-check)'), ('reviewed', 'Human-reviewed / confirmed'), ('estimated', 'Estimated (no direct FDC match — e.g. branded approximation)'), ('no_match', 'No usable match (reviewed, left blank)')], help_text='Provenance of the macro profile — mirrors match_confidence. Drives the coverage % in the provided-nutrition rollup so the number never overstates its own accuracy.', max_length=20),
        ),
    ]
